language: perl
sudo: false             # faster builds as long as you don't need sudo access
addons:
  apt:
    packages:
      - aspell
      - aspell-en
language: perl
perl:
  - "blead"
  - "blead-thr"
  - "5.28"
  - "5.28-thr"
  - "5.26"
  - "5.26-thr"
  - "5.24"
  - "5.24-thr"
  - "5.22"
  - "5.22-thr"
  - "5.20"
  - "5.20-thr"
  - "5.18"
  - "5.18-thr"
  - "5.16"
  - "5.16-thr"
  - "5.14"
  - "5.14-thr"
  - "5.12"
  - "5.12-thr"
  - "5.10"
  - "5.10-thr"
  - "5.8"
  - "5.8-thr"
matrix:
  include:
    - perl: 5.24
      env: COVERAGE=1   # enables coverage+coveralls reporting
  allow_failures:
    - perl: blead       # ignore failures for blead perl
env:
  global:
    - AUTHOR_TESTING=1
    - AUTOMATED_TESTING=1
    - RELEASE_TESTING=1
    - PERL_CPANM_OPT=--with-suggests
      # this is fake, but it only needs to be defined in order to compile LWP::Protocol::mailto
    - SENDMAIL=/usr/sbin/sendmail
before_install:
  - git clone git://github.com/travis-perl/helpers ~/travis-perl-helpers
  - source ~/travis-perl-helpers/init
  - build-perl
  - perl -V
  - build-dist
  - cd $BUILD_DIR             # $BUILD_DIR is set by the build-dist command
install:
  - cpan-install --deps       # installs prereqs, including optional modules
  - cpan-install --coverage   # installs converage prereqs, if enabled
before_script:
  - coverage-setup
script:
  - "sed -r -i -e 's/^s*\\{\\{\\$NEXT}}$/{{$NEXT}}\\n    - /' Changes"
  - perl Makefile.PL
  - make
  - prove -b -r -s -j$(test-jobs) $(test-files)
after_success:
  - coverage-report
